[workspace]
resolver = "3"
members = ["tools/*"]

[workspace.package]
edition = "2021" # "2024" does not compile.
version = "2.1.1"
repository = "https://github.com/Talus-Network/nexus-tools"
homepage = "https://talus.network"
license = "Apache-2.0"
readme = "README.md"
authors = ["Talus Engineering <engineering@taluslabs.xyz>"]
keywords = ["nexus", "talus", "tools", "walrus"]
categories = []

[workspace.dependencies]
anyhow = "1.0.102"
bytes = "1.11.1"
dotenvy = "0.15.7"
ed25519-dalek = "2.2.0"
env_logger = "0.11.10"
hex = "0.4.3"
jsonschema = { version = "0.46.10", default-features = false }
sha2 = "0.11.0"
chrono = { version = "0.4.44", features = ["serde"] }
log = "0.4.29"
minijinja = { version = "2.21.0", features = ["fuel", "json", "unstable_machinery"] }
mockito = "1.7.2"
rand = "0.8"
reqwest = { version = "0.12.25", features = ["json", "stream", "gzip", "brotli"] }
schemars = "1.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
url = "2.5.8"
uuid = { version = "1.23.1", features = ["v4"] }
warp = "0.4.3"
zeroize = { version = "1", features = ["zeroize_derive"] }

# === Nexus deps ===
[workspace.dependencies.nexus-sdk]
version = "2.1.1"

[workspace.dependencies.nexus-toolkit]
version = "2.1.1"


[profile.release]
# debug = 1 means line charts only, which is minimum needed for good stack traces
debug = 1
# Write debug info into a separate file.
split-debuginfo = "packed"
# Decrease final binary size
strip = "debuginfo"
# Let the toolkit contain invocation panics within the failing request.
panic = "unwind"
